import Header from '@/Components/nav'
import Head from 'next/head'
import Footer from '@/Components/footer';
import 'bootstrap/dist/css/bootstrap.css'
import Aboutsection2 from '/src/Components/about-section2'
import Aboutqualification from '@/Components/about-qualificationjs';
const AboutUsPage = () => {
    return (
        <>
        <Head>
        <title>AerrowDev &#124; About</title>
         <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
     
         </Head>
          <main>
          
          <Header/>
       <Aboutsection2/>
       <Aboutqualification/>
          </main>
           <Footer />

      </>
    )
}
export default AboutUsPage;
