import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import Imagenav from '/src/Components/logo-nav'
import Aboutsection from '@/Components/about-section'
import Aboutsection2 from '@/Components/about-section2'
import Header from '@/Components/nav'
import Footer from '@/Components/footer'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head >
        <title>AerrowDev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/favicon.png" />
        </Head>
  
        <main>
        
        <Header/>
      <Aboutsection/>
      
        </main>
         <Footer/>
    </>
  )
}
