import Header from '@/Components/nav'
import Head from 'next/head'
import Footer from '@/Components/footer';
import 'bootstrap/dist/css/bootstrap.css'
import PortfolioPages from '/src/Components/Portfolio'
const PortfolioPage = () => {
    return (
        <>
        <Head>
        <title>AerrowDev &#124; Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/favicon.png" />
         </Head>
          <main>
          <Header/>
        <PortfolioPages/>
          </main> 
           <Footer />
         
      </>
    )
}
export default PortfolioPage;